using System;

namespace Laan.Sql.Parser
{
    public class Constants
    {
        public const string Assignment = "=";
        public const string OpenBracket = "(";
        public const string CloseBracket = ")";

        public const string Add = "ADD";
        public const string All = "ALL";
        public const string Alter = "ALTER";
        public const string And = "AND";
        public const string As = "AS";
        public const string Ascending = "ASC";
        public const string Begin = "BEGIN";
        public const string Between = "BETWEEN";
        public const string By = "BY";
        public const string Case = "CASE";
        public const string Clustered = "CLUSTERED";
        public const string Collate = "COLLATE";
        public const string Comma = ",";
        public const string Commit = "COMMIT";
        public const string Constraint = "CONSTRAINT";
        public const string Create = "CREATE";
        public const string Declare = "DECLARE";
        public const string Default = "DEFAULT";
        public const string Delete = "DELETE";
        public const string Descending = "DESC";
        public const string Distinct = "DISTINCT";
        public const string Distributed = "DISTRIBUTED";
        public const string Dot = ".";
        public const string Else = "ELSE";
        public const string End = "END";
        public const string Except = "EXCEPT";
        public const string Exec = "EXEC";
        public const string Exists = "EXISTS";
        public const string Foreign = "FOREIGN";
        public const string From = "FROM";
        public const string Full = "FULL";
        public const string Go = "GO";
        public const string Grant = "GRANT";
        public const string Group = "GROUP";
        public const string Having = "HAVING";
        public const string Identity = "IDENTITY";
        public const string If = "IF";
        public const string In = "IN";
        public const string Index = "INDEX";
        public const string Intersect = "INTERSECT";
        public const string Inner = "INNER";
        public const string Insert = "INSERT";
        public const string Into = "INTO";
        public const string Join = "JOIN";
        public const string Key = "KEY";
        public const string Left = "LEFT";
        public const string Like = "LIKE";
        public const string NoCheck = "NOCHECK";
        public const string NonClustered = "NONCLUSTERED";
        public const string Not = "NOT";
        public const string Null = "NULL";
        public const string On = "ON";
        public const string Or = "OR";
        public const string Order = "ORDER";
        public const string Outer = "OUTER";
        public const string Percent = "PERCENT";
        public const string Primary = "PRIMARY";
        public const string Print = "PRINT";
        public const string Procedure = "PROCEDURE";
        public const string References = "REFERENCES";
        public const string Right = "RIGHT";
        public const string Rollback = "ROLLBACK";
        public const string Select = "SELECT";
        public const string SemiColon = ";";
        public const string Set = "SET";
        public const string Table = "TABLE";
        public const string Tran = "TRAN";
        public const string Transaction = "TRANSACTION";
        public const string Then = "THEN";
        public const string To = "TO";
        public const string Top = "TOP";
        public const string Union = "UNION";
        public const string Unique = "UNIQUE";
        public const string Update = "UPDATE";
        public const string Values = "VALUES";
        public const string View = "VIEW";
        public const string When = "WHEN";
        public const string Where = "WHERE";
        public const string With = "WITH";
        public const string Work = "WORK";
    }
}
